# Generated by Django 3.2.9 on 2021-12-28 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing_bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='listings_bid', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommmentListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateTimeField(auto_now=True)),
                ('comment_text', models.CharField(max_length=256)),
                ('listing_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_comment', to='auctions.listing')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
