# Generated by Django 3.2.9 on 2021-12-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211228_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
