# Generated by Django 3.2.9 on 2022-01-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_comment',
            new_name='listing_watchlist',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_comment',
            new_name='user_watchlist',
        ),
    ]
