# Generated by Django 3.2.9 on 2022-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20220104_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_watchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_watchlist',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
