# Generated by Django 3.2.9 on 2022-01-04 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20220104_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user_watchlist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
