# Generated by Django 3.2.9 on 2022-01-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_watchlist_user_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winnerlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_msg', models.BooleanField(default=True)),
                ('listing_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_winner', to='auctions.listing')),
                ('user_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
