# Generated by Django 3.2.9 on 2022-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_winnerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_listing',
            field=models.URLField(blank=True, null=True),
        ),
    ]
